#+TITLE:  Joao Azevedo's Emacs Initialization File
#+AUTHOR: Joao Azevedo
#+EMAIL:  joao.c.azevedo@gmail.com
#+DATE:   2015-06-12 Fri

  This file is my Emacs initialization file. It's written in [[http://orgmode.org/][org-mode]] using
  [[http://orgmode.org/worg/org-contrib/babel/][org-babel]]. The idea behind using org-mode (and org-babel) is to keep it both
  documented and organized. It is currently built as a single =.org= file, but I
  aim to eventually make it more modular. This configuration reflects my
  personal preferences when using Emacs.

  I use Emacs primarily on Mac OS X, using the Emacs mac port [[http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git/][from Yamamoto
  Mitsuharu]], which I usually install and update using [[http://brew.sh/][Homebrew]] and [[https://github.com/railwaycat/homebrew-emacsmacport][this
  formulae]].

  The latest Emacs version that I've run this configuration with is =24.5.1=.

** Table of Contents                                                  :TOC_3:
     - [[#core][Core]]
         - [[#global-variables][Global Variables]]
     - [[#packages][Packages]]
     - [[#ui][UI]]
     - [[#editor][Editor]]
     - [[#version-control][Version control]]
     - [[#text][Text]]
         - [[#org][Org]]

** Core

   The following options are relevant throughout the whole config and relate to
   core settings for Emacs.

   The =load-prefer-newer= option was introduced in Emacs 24.4 and allows one to
   specify how the =load= function chooses the files to load. By default its
   value is =nil=, which means that, in the presence of both an =.el= and =.elc=
   file with the same name, the =load= function will always prefer the =.elc=. I
   want to avoid loading outdated =.elc= files, so this option is set to =t=.

#+BEGIN_SRC emacs-lisp
  (setq load-prefer-newer t)
#+END_SRC

   By default, garbage collection happens every 0.76MB of allocated data. This
   sets it to happen on each 50MB.

#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold 50000000)
#+END_SRC

   The following produces a warning when opening files bigger than 100MB.

#+BEGIN_SRC emacs-lisp
  (setq large-file-warning-threshold 100000000)
#+END_SRC

*** Global Variables

    The following block defines variables that are used throughout the whole
    initialization file. The variables are usually prefixed with =jcazevedo/=.

#+BEGIN_SRC emacs-lisp
  (defvar jcazevedo/config-dir (file-name-directory load-file-name))
  (defvar jcazevedo/elpa-dir (expand-file-name "elpa" jcazevedo/config-dir))
#+END_SRC

    The following variables are defined:

| Variable Name          | Variable Description                           |
|------------------------+------------------------------------------------|
| =jcazevedo/config-dir= | The directory where the initialization file is |

** Packages

   The following options are related to the installation of packages required by
   this config.

   =package.el= is the built-in package manager in Emacs 24.

#+BEGIN_SRC emacs-lisp
  (require 'package)
#+END_SRC

   Update the package archives to include the default package archive (=gnu=),
   as well as =marmalde= and =melpa=.

#+BEGIN_SRC emacs-lisp
  (setq package-archives
        '(("gnu" . "http://elpa.gnu.org/packages/")
          ("marmalade" . "https://marmalade-repo.org/packages/")
          ("melpa" . "http://melpa.org/packages/")))
#+END_SRC

#+BEGIN_SRC emacs-lip
  (setq package-user-dir jcazevedo/elpa-dir)
  (package-initialize)

  (defun jcazevedo/require-package (package)
    (unless (package-installed-p package)
      (package-install package)))

  (defun jcazevedo/require-packages (packages)
    (mapc #'jcazevedo/require-package packages))
#+END_SRC

** UI

#+BEGIN_SRC emacs-lisp
  (when (fboundp 'tool-bar-mode)
    (tool-bar-mode -1))

  (menu-bar-mode -1)

  (setq scroll-margin 0
        scroll-conservatively 100000
        scroll-preserve-screen-position 1)

  (line-number-mode t)
  (column-number-mode t)
  (size-indication-mode t)

  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (jcazevedo/require-packages '(zenburn-theme))
  (load-theme 'zenburn t)
#+END_SRC

** Editor

#+BEGIN_SRC emacs-lisp
  (setq-default indent-tabs-mode nil)
  (setq-default tab-width 8)
  (setq require-final-newline t)
  (delete-selection-mode t)
  (setq backup-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq auto-save-file-name-transforms
        `((".*" ,temporary-file-directory t)))
  (setq undo-tree-history-directory-alist
        `((".*" . ,temporary-file-directory)))
  (setq undo-tree-auto-save-history t)
  (global-auto-revert-mode t)
  (global-hl-line-mode +1)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (require 'uniquify)
  (setq uniquify-buffer-name-style 'forward)
  (setq uniquify-separator "/")
  (setq uniquify-after-kill-buffer-p t)
  (setq uniquify-ignore-buffers-re "^\\*")
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (defun jcazevedo/cleanup-maybe ()
    (whitespace-cleanup))

  (defun jcazevedo/enable-whitespace ()
    (add-hook 'before-save-hook 'jcazevedo/cleanup-maybe nil t)
    (whitespace-mode +1))

  (require 'whitespace)
  (setq whitespace-line-column 80)
  (setq-default fill-column 80)
  (setq whitespace-style '(face tabs empty trailing))

  (jcazevedo/require-packages '(fill-column-indicator))
#+END_SRC

** Version control

#+BEGIN_SRC emacs-lisp
  (jcazevedo/require-packages '(magit))
  (setq magit-last-seen-setup-instructions "1.4.0")
  (global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC

** Text

#+BEGIN_SRC emacs-lisp
  (add-hook 'text-mode-hook 'fci-mode)
  (add-hook 'text-mode-hook 'jcazevedo/enable-whitespace)
#+END_SRC

*** Org

#+BEGIN_SRC emacs-lisp
(jcazevedo/require-packages '(toc-org))

(require 'toc-org)
(add-hook 'org-mode-hook 'toc-org-enable)
#+END_SRC
